export default {
  development: {
    username: "taskfluxeuser",
    password: "saad@1234",
    database: "taskfluxedb",
    host: "db4free.net",
    port: 3306,
    dialect: "mysql",
    logging: true,
    freezeTableName: true,
    migrationStorage: "json",
    migrationStoragePath: "sequelizeMeta.json",
    migrationStorageTableName: "sequelize_meta",
    migrationStorageTableSchema: "custom_schema",
  },
  test: {
    username: "root",
    password: null,
    database: "database_test",
    host: "127.0.0.1",
    dialect: "mysql",
  },
  production: {
    username: "root",
    password: null,
    database: "database_production",
    host: "127.0.0.1",
    dialect: "mysql",
  },
};

// username: "taskfluxeuser",
// password: "saad@1234",
// database: "taskfluxedb",
// host: "db4free.net",
// port: 3306,
// dialect: "mysql",
// logging: true,
// migrationStorage: "json",
// migrationStoragePath: "sequelizeMeta.json",
// migrationStorageTableName: "sequelize_meta",
// migrationStorageTableSchema: "custom_schema",
